import {
    OpenAPIRegistry,
    OpenApiGeneratorV3
} from '@asteasolutions/zod-to-openapi'
import { extendZodWithOpenApi } from '@asteasolutions/zod-to-openapi'
import { z } from 'zod'
import { env } from '../../env'

extendZodWithOpenApi(z)
export { z }
export const registry = new OpenAPIRegistry()
registry.registerComponent('securitySchemes', 'bearerAuth', {
    type: 'http',
    scheme: 'bearer',
    bearerFormat: 'JWT'
})

export function getOpenApiDocumentation() {
    const generator = new OpenApiGeneratorV3(registry.definitions)

    return generator.generateDocument({
        openapi: '3.0.0',
        info: {
            version: '1.0.0',
            title: 'Foddies API',
            description: 'Autogenerated API documentation'
        },
        servers: [
            {
                url: `http://localhost:${env.PORT}/api/v1`,
                description: 'Localhost (Development)'
            },
            {
                url: `https://foddies-backend.onrender.com/api/v1`,
                description: 'Production (Render)'
            }
        ]
    })
}
