import {
    OpenAPIRegistry,
    OpenApiGeneratorV3
} from '@asteasolutions/zod-to-openapi'
import * as extendZod from '@asteasolutions/zod-to-openapi'
import { z } from 'zod'
import { env } from '../../env'

extendZod.extendZodWithOpenApi(z)

export const registry = new OpenAPIRegistry()

export function getOpenApiDocumentation() {
    const generator = new OpenApiGeneratorV3(registry.definitions)

    return generator.generateDocument({
        openapi: '3.0.0',
        info: {
            version: '1.0.0',
            title: 'Foddies API',
            description: 'Autogenerated API documentation'
        },
        servers: [{ url: `http://localhost:${env.PORT}/api/v1` }]
    })
}
